spring:
  application:
    name: legal-advisory-service
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
  ai:
    openai:
      api-key: ${OPENAI_API_KEY}
      chat:
        options:
          model: gpt-3.5-turbo
document:
  upload-location: ${DOC_UPLOAD_LOCATION}
  vector-store-file-location: ${VECTOR_STORE_LOCATION}